export const EDITOR_LOCALES = ["zh", "en"] as const;

export type EditorLocale = (typeof EDITOR_LOCALES)[number];

export function isEditorLocale(value: string): value is EditorLocale {
  return EDITOR_LOCALES.includes(value as EditorLocale);
}

export const editorCopy = {
  zh: {
    meta: {
      title: "编辑器 | Vibe Screen",
      description: "在浏览器录制、编辑并导出高质量视频。",
    },
    loading: "正在打开本地编辑器...",
    toolbar: {
      backHome: "返回 Vibe Screen 首页",
      projectName: "工程名称",
      undo: "撤销",
      redo: "重做",
      saving: "正在保存",
      saveFailed: "本地保存失败",
      saved: "已保存到本地",
      record: "录制",
      export: "导出",
      language: "切换编辑器语言",
    },
    media: {
      aria: "工程媒体",
      project: "工程",
      media: "媒体",
      newProject: "新建工程",
      record: "录制",
      import: "导入",
      assets: "素材",
      importing: "正在导入媒体",
      noMedia: "还没有媒体",
      noMediaBody: "录制屏幕，或导入浏览器支持的视频。",
      localProject: "本地工程",
      localBody: "媒体不会离开此浏览器",
      removeAsset: (name: string) => `移除 ${name}`,
      importError: "所选媒体无法导入。",
    },
    canvas: {
      fit: "适应画布",
      zoom: "画布缩放",
      preview: "视频合成预览",
      emptyTitle: "开始录制第一个场景",
      emptyBody: "录制标签页、窗口或整个屏幕，也可以从媒体区导入现有视频。",
      startRecording: "开始录制",
      importVideo: "导入视频",
      play: "播放",
      pause: "暂停",
    },
    timeline: {
      aria: "时间线编辑器",
      addZoom: "添加缩放",
      addText: "添加文字",
      zoom: "时间线缩放",
      screen: "屏幕",
      text: "文字",
      empty: "录制或导入媒体后即可开始编辑时间线。",
    },
    inspector: {
      aria: "检查器",
      sections: "检查器分区",
      panel: {
        media: "片段",
        canvas: "画布",
        text: "文字",
        zoom: "缩放",
        export: "导出",
      },
      clip: {
        noSelectedTitle: "未选择片段",
        noSelectedBody: "录制或导入视频后即可调整时间范围。",
        title: "屏幕片段",
        description: "设置可用范围，不会修改源文件。",
        trim: "裁剪范围",
        in: "入点",
        out: "出点",
        trimIn: "裁剪入点",
        trimOut: "裁剪出点",
        camera: "摄像头叠层",
        showCamera: "显示摄像头",
        size: "大小",
        x: "X",
        y: "Y",
        shape: "形状",
        circle: "圆形",
        rounded: "圆角",
        square: "方形",
        mirror: "镜像摄像头",
      },
      canvasPanel: {
        title: "画布",
        description: "调整构图，同时保持源素材清晰。",
        ratio: "画幅比例",
        original: "原始",
        wide: "宽屏",
        vertical: "竖屏",
        square: "方形",
        classic: "经典",
        background: "背景",
        solid: "纯色",
        gradient: "渐变",
        color: "颜色",
        from: "起始色",
        to: "结束色",
        angle: "角度",
        frame: "画面",
        padding: "留白",
        radius: "圆角半径",
        shadow: "阴影",
      },
      textPanel: {
        title: "文字",
        description: "添加简洁的字幕、标注和标题。",
        noSelectedTitle: "未选择文字",
        noSelectedBody: "在当前播放头位置创建文字层。",
        add: "添加文字",
        layerTitle: "文字层",
        layerDescription: "导出前都可以继续编辑文字。",
        content: "内容",
        text: "文字",
        timing: "时间",
        start: "开始",
        end: "结束",
        typography: "字体",
        size: "字号",
        weight: "字重",
        color: "文字颜色",
        position: "位置",
        x: "X",
        y: "Y",
        width: "宽度",
        remove: "移除文字层",
      },
      zoomPanel: {
        title: "缩放",
        description: "无需重新录制，也能把注意力引向重点。",
        noSelectedTitle: "未选择缩放",
        noSelectedBody: "在当前播放头位置创建平滑的聚焦片段。",
        add: "添加缩放",
        regionTitle: "缩放区域",
        regionDescription: "聚焦画面重点，同时保持画布尺寸不变。",
        timing: "时间",
        start: "开始",
        end: "结束",
        focus: "焦点",
        scale: "倍率",
        x: "X",
        y: "Y",
        remove: "移除缩放区域",
      },
      exportPanel: {
        title: "导出",
        description: "使用浏览器支持的最佳编码器在本地渲染画布。",
        output: "输出",
        resolution: "分辨率",
        source: "源分辨率",
        fourK: "4K",
        bitrate: "码率",
        localRender: "本地渲染",
        exportVideo: "导出视频",
        note: "第一版使用实时渲染，以保证跨浏览器的音频与画面合成一致。",
      },
    },
    recorder: {
      kicker: "浏览器录制",
      setupTitle: "开始新的录制",
      recordingTitle: "正在录制",
      close: "关闭录制器",
      chooseTitle: "点击录制后选择来源",
      chooseBody: "浏览器会请求选择标签页、窗口或整个屏幕。",
      frameRate: "录制帧率",
      microphone: "麦克风",
      microphoneDetail: "已开启降噪",
      sharedAudio: "共享音频",
      sharedAudioDetail: "是否可用取决于所选录制来源",
      camera: "摄像头",
      cameraDetail: "会作为可编辑叠层录制",
      chooseAndRecord: "选择屏幕并录制",
      pause: "暂停",
      resume: "继续",
      preparing: "正在准备编辑器...",
      stop: "停止录制",
      privacy: "媒体保存在此设备上。Vibe Screen 不会上传任何内容。",
      accessError: "未获得屏幕权限。请选择标签页、窗口或整个屏幕后重试。",
      saveError: "录制无法保存。",
    },
    exportDialog: {
      kicker: "本地渲染",
      title: "导出 Vibe Screen 视频",
      readyTitle: "视频已经准备好",
      close: "关闭导出窗口",
      completed: "导出完成",
      completedBody: "编码文件已保存，工程没有上传。",
      saveAnother: "再保存一份",
      resolution: "分辨率",
      frameRate: "帧率",
      bitrate: "码率",
      preparing: "正在准备媒体",
      finalizing: "正在整理文件",
      rendering: "正在渲染画面",
      retry: "重新导出",
      start: "开始导出",
      renderingButton: "正在渲染...",
      privacy: "实时渲染期间请保持此标签页处于打开状态。",
      error: "视频无法导出。",
    },
  },
  en: {
    meta: {
      title: "Studio | Vibe Screen",
      description: "Record, edit, and export polished screen videos in your browser.",
    },
    loading: "Opening your local studio...",
    toolbar: {
      backHome: "Back to Vibe Screen home",
      projectName: "Project name",
      undo: "Undo",
      redo: "Redo",
      saving: "Saving",
      saveFailed: "Local save failed",
      saved: "Saved locally",
      record: "Record",
      export: "Export",
      language: "Switch editor language",
    },
    media: {
      aria: "Project media",
      project: "Project",
      media: "Media",
      newProject: "New project",
      record: "Record",
      import: "Import",
      assets: "Assets",
      importing: "Importing media",
      noMedia: "No media yet",
      noMediaBody: "Record your screen or import a browser-compatible video.",
      localProject: "Local project",
      localBody: "Media never leaves this browser",
      removeAsset: (name: string) => `Remove ${name}`,
      importError: "The selected media could not be imported.",
    },
    canvas: {
      fit: "Fit canvas",
      zoom: "Canvas zoom",
      preview: "Video composition preview",
      emptyTitle: "Capture your first scene",
      emptyBody: "Record a tab, window, or display. You can also import an existing video from the media panel.",
      startRecording: "Start recording",
      importVideo: "Import video",
      play: "Play",
      pause: "Pause",
    },
    timeline: {
      aria: "Timeline editor",
      addZoom: "Add zoom",
      addText: "Add text",
      zoom: "Timeline zoom",
      screen: "Screen",
      text: "Text",
      empty: "Record or import media to build a timeline.",
    },
    inspector: {
      aria: "Inspector",
      sections: "Inspector sections",
      panel: {
        media: "Clip",
        canvas: "Canvas",
        text: "Text",
        zoom: "Zoom",
        export: "Export",
      },
      clip: {
        noSelectedTitle: "No clip selected",
        noSelectedBody: "Record or import a video to edit its timing.",
        title: "Screen clip",
        description: "Set the usable range without changing your source file.",
        trim: "Trim range",
        in: "In",
        out: "Out",
        trimIn: "Trim in",
        trimOut: "Trim out",
        camera: "Camera overlay",
        showCamera: "Show camera",
        size: "Size",
        x: "X",
        y: "Y",
        shape: "Shape",
        circle: "Circle",
        rounded: "Rounded",
        square: "Square",
        mirror: "Mirror camera",
      },
      canvasPanel: {
        title: "Canvas",
        description: "Shape the composition and keep the source sharp.",
        ratio: "Aspect ratio",
        original: "Original",
        wide: "Wide",
        vertical: "Vertical",
        square: "Square",
        classic: "Classic",
        background: "Background",
        solid: "Solid",
        gradient: "Gradient",
        color: "Color",
        from: "From",
        to: "To",
        angle: "Angle",
        frame: "Frame",
        padding: "Padding",
        radius: "Corner radius",
        shadow: "Shadow",
      },
      textPanel: {
        title: "Text",
        description: "Add concise captions, callouts, and titles.",
        noSelectedTitle: "No text selected",
        noSelectedBody: "Create a text layer at the current playhead.",
        add: "Add text",
        layerTitle: "Text layer",
        layerDescription: "Text remains editable until export.",
        content: "Content",
        text: "Text",
        timing: "Timing",
        start: "Start",
        end: "End",
        typography: "Typography",
        size: "Size",
        weight: "Weight",
        color: "Text color",
        position: "Position",
        x: "X",
        y: "Y",
        width: "Width",
        remove: "Remove text layer",
      },
      zoomPanel: {
        title: "Zoom",
        description: "Direct attention without re-recording.",
        noSelectedTitle: "No zoom selected",
        noSelectedBody: "Create a smooth focus region at the playhead.",
        add: "Add zoom",
        regionTitle: "Zoom region",
        regionDescription: "Focus a point while preserving the canvas size.",
        timing: "Timing",
        start: "Start",
        end: "End",
        focus: "Focus",
        scale: "Scale",
        x: "X",
        y: "Y",
        remove: "Remove zoom region",
      },
      exportPanel: {
        title: "Export",
        description: "Render the canvas locally with the best codec your browser exposes.",
        output: "Output",
        resolution: "Resolution",
        source: "Source",
        fourK: "4K",
        bitrate: "Bitrate",
        localRender: "Local render",
        exportVideo: "Export video",
        note: "The first release renders in real time for consistent cross-browser audio and visual composition.",
      },
    },
    recorder: {
      kicker: "Browser capture",
      setupTitle: "Start a new recording",
      recordingTitle: "Recording in progress",
      close: "Close recorder",
      chooseTitle: "Choose after you click record",
      chooseBody: "Your browser will ask for a tab, window, or display.",
      frameRate: "Capture frame rate",
      microphone: "Microphone",
      microphoneDetail: "Noise suppression on",
      sharedAudio: "Shared audio",
      sharedAudioDetail: "Availability depends on the selected source",
      camera: "Camera",
      cameraDetail: "Recorded as an editable overlay",
      chooseAndRecord: "Choose screen and record",
      pause: "Pause",
      resume: "Resume",
      preparing: "Preparing editor...",
      stop: "Stop recording",
      privacy: "Media stays on this device. Nothing is uploaded by Vibe Screen.",
      accessError: "Screen access was not granted. Choose a tab, window, or display and try again.",
      saveError: "The recording could not be saved.",
    },
    exportDialog: {
      kicker: "Local render",
      title: "Export Vibe Screen video",
      readyTitle: "Your video is ready",
      close: "Close export",
      completed: "Export completed",
      completedBody: "The encoded file was saved without uploading your project.",
      saveAnother: "Save another copy",
      resolution: "Resolution",
      frameRate: "Frame rate",
      bitrate: "Bitrate",
      preparing: "Preparing media",
      finalizing: "Finalizing file",
      rendering: "Rendering frames",
      retry: "Try export again",
      start: "Start export",
      renderingButton: "Rendering...",
      privacy: "Keep this tab active during the real-time render.",
      error: "The video could not be exported.",
    },
  },
} as const;

export type EditorCopy = (typeof editorCopy)[EditorLocale];
