export const LANDING_LOCALES = ["zh", "en"] as const;

export type LandingLocale = (typeof LANDING_LOCALES)[number];

export function isLandingLocale(value: string): value is LandingLocale {
  return LANDING_LOCALES.includes(value as LandingLocale);
}

export const landingCopy = {
  zh: {
    meta: {
      title: "Vibe Screen | 在线录屏与视频编辑器",
      description: "直接在浏览器录制、编辑并导出清晰的产品演示、教程和操作视频，素材与工程默认保存在本地。",
      openGraph: "在浏览器完成录屏、剪辑和高质量导出，无需上传原始素材。",
    },
    nav: {
      aria: "主要导航",
      workflow: "工作流程",
      features: "功能",
      privacy: "隐私",
      studio: "打开编辑器",
      language: "切换界面语言",
    },
    hero: {
      eyebrow: "录制。剪辑。发布。",
      title: "把屏幕录制，剪成好视频。",
      description: "直接在浏览器录制、精修并导出清晰的产品演示、教程和操作视频。",
      primary: "开始录制",
      secondary: "查看流程",
      product: "Vibe Screen 编辑器",
      localProject: "本地工程",
      imageAlt: "Vibe Screen 编辑器，包含素材目录、视频画布、右侧配置和时间线",
      captureNote: "浏览器录制",
      localNote: "默认保存在本地",
    },
    capability: {
      checking: "正在检查浏览器能力...",
      ready: "当前浏览器可以录制",
      warning: "建议使用 Chrome 或 Edge 录制",
    },
    principles: {
      aria: "产品原则",
      upload: "无需上传素材",
      source: "最高支持 4K 源录制",
      export: "浏览器本地导出",
      focus: "可编辑聚焦与缩放",
    },
    workflow: {
      title: "从录制到成片，一条清晰流程。",
      description: "专为产品演示、教程和操作讲解设计。",
      captureTitle: "选对录制来源",
      captureBody: "选择标签页、窗口或屏幕，按需加入麦克风、共享音频和独立摄像头图层。",
      captureAlt: "Vibe Screen 录制窗口，包含麦克风、共享音频、摄像头与帧率设置",
      editTitle: "简洁剪辑，不打断思路",
      editBody: "裁剪片段、添加聚焦缩放与文字提示，并在紧凑时间线上调整画面。",
      editAlt: "Vibe Screen 时间线，包含屏幕、缩放和文字轨道",
      exportTitle: "本机完成导出",
      exportBody: "以 30 或 60 fps 本地渲染，并精确设置分辨率与码率。",
    },
    features: {
      title: "把专业能力放在关键地方。",
      description: "第一版保持核心轻巧、快速、可靠。",
      canvasTitle: "真正的编辑画布",
      canvasBody: "调整画幅、留白、圆角、阴影、背景和同步摄像头叠层。",
      focusTitle: "时间线聚焦效果",
      focusBody: "添加可调倍率与焦点位置的缩放片段，导出前即可完整预览。",
      localTitle: "本地优先工程",
      localBody: "工程数据与原始素材保存在 IndexedDB，不会上传到 Vibe Screen 服务器。",
      qualityTitle: "清晰度控制",
      qualityBody: "可选源分辨率、1080p、1440p 或 4K，并分别设置帧率与码率。",
    },
    privacy: {
      title: "你的原始素材，只属于你。",
      body: "录制、工程保存、预览和导出都在本机完成。制作视频无需注册 Vibe Screen 账号。",
      upload: "不上传原始素材",
      account: "无需账号",
      source: "开源项目",
    },
    closing: {
      title: "让下一段演示值得看完。",
      body: "打开编辑器，选择要分享的屏幕，继续完成剪辑。",
      action: "打开编辑器",
    },
    footer: "专为高质量浏览器录屏与剪辑打造。",
  },
  en: {
    meta: {
      title: "Vibe Screen | Record beautifully in your browser",
      description: "A private, local-first browser screen recorder and editor for polished product demos, tutorials, and walkthroughs.",
      openGraph: "Record, edit, and export polished screen videos without leaving your browser.",
    },
    nav: {
      aria: "Primary navigation",
      workflow: "Workflow",
      features: "Features",
      privacy: "Privacy",
      studio: "Open studio",
      language: "Switch interface language",
    },
    hero: {
      eyebrow: "Record. Refine. Publish.",
      title: "Your screen, edited with intention.",
      description: "Capture crisp demos, shape every frame, and export polished video directly in your browser.",
      primary: "Start recording",
      secondary: "See the workflow",
      product: "Vibe Screen Studio",
      localProject: "Local project",
      imageAlt: "Vibe Screen editor showing the media directory, video canvas, inspector, and timeline",
      captureNote: "Browser capture",
      localNote: "Local by default",
    },
    capability: {
      checking: "Checking this browser...",
      ready: "This browser is ready to record",
      warning: "Chrome or Edge is recommended for recording",
    },
    principles: {
      aria: "Product principles",
      upload: "No upload required",
      source: "Up to 4K source capture",
      export: "Browser-native export",
      focus: "Editable zoom and focus",
    },
    workflow: {
      title: "From capture to a finished cut.",
      description: "A focused workflow for product demos, tutorials, and walkthroughs.",
      captureTitle: "Capture the right source",
      captureBody: "Choose a tab, window, or display. Add microphone, shared audio, and a separately editable camera layer.",
      captureAlt: "Vibe Screen browser capture dialog with microphone, shared audio, camera, and frame-rate controls",
      editTitle: "Cut without clutter",
      editBody: "Trim the clip, place focus zooms, add text callouts, and adjust the frame in a compact timeline.",
      editAlt: "Vibe Screen timeline with screen, zoom, and text tracks",
      exportTitle: "Export on your machine",
      exportBody: "Render the final composition locally at 30 or 60 fps with resolution and bitrate controls.",
    },
    features: {
      title: "Professional where it matters.",
      description: "The first release keeps the core small, fast, and dependable.",
      canvasTitle: "Real editing canvas",
      canvasBody: "Aspect ratios, padding, radii, shadows, backgrounds, and synchronized camera overlays.",
      focusTitle: "Timeline focus effects",
      focusBody: "Place zoom regions with adjustable scale and focal point, then preview them before export.",
      localTitle: "Local-first projects",
      localBody: "Draft metadata and source blobs persist in IndexedDB. Nothing is sent to a Vibe Screen server.",
      qualityTitle: "Quality controls",
      qualityBody: "Choose source, 1080p, 1440p, or 4K output with explicit frame rate and bitrate.",
    },
    privacy: {
      title: "Your raw footage stays yours.",
      body: "Recording, project storage, preview, and export run locally. Vibe Screen does not need an account to make a video.",
      upload: "No source upload",
      account: "No account required",
      source: "Open-source project",
    },
    closing: {
      title: "Make the next demo worth watching.",
      body: "Open the studio, choose your screen, and keep the edit moving.",
      action: "Open studio",
    },
    footer: "Built for focused browser-native screen video.",
  },
} as const;
